# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcMiner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpcMiner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpcMiner.proto\"\x07\n\x05\x45mpty\"\x1b\n\rTransactionID\x12\n\n\x02id\x18\x01 \x01(\x05\"6\n\tChallenge\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\x12\x12\n\ndifficulty\x18\x02 \x01(\x05\"/\n\x06Status\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\"1\n\x06Winner\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\x12\x10\n\x08\x63lientID\x18\x02 \x01(\x05\"Z\n\x0cSolutionInfo\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\x12\x11\n\tchallenge\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\x12\x0e\n\x06winner\x18\x04 \x01(\x05\"J\n\rSubmitRequest\x12\x15\n\rtransactionID\x18\x01 \x01(\x05\x12\x10\n\x08\x63lientID\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\"\x1e\n\x0eSubmitResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x32\x9c\x02\n\tMinerador\x12*\n\x10getTransactionID\x12\x06.Empty\x1a\x0e.TransactionID\x12*\n\x0cgetChallenge\x12\x0e.TransactionID\x1a\n.Challenge\x12/\n\x14getTransactionStatus\x12\x0e.TransactionID\x1a\x07.Status\x12$\n\tgetWinner\x12\x0e.TransactionID\x1a\x07.Winner\x12,\n\x0bgetSolution\x12\x0e.TransactionID\x1a\r.SolutionInfo\x12\x32\n\x0fsubmitChallenge\x12\x0e.SubmitRequest\x1a\x0f.SubmitResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcMiner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=19
  _globals['_EMPTY']._serialized_end=26
  _globals['_TRANSACTIONID']._serialized_start=28
  _globals['_TRANSACTIONID']._serialized_end=55
  _globals['_CHALLENGE']._serialized_start=57
  _globals['_CHALLENGE']._serialized_end=111
  _globals['_STATUS']._serialized_start=113
  _globals['_STATUS']._serialized_end=160
  _globals['_WINNER']._serialized_start=162
  _globals['_WINNER']._serialized_end=211
  _globals['_SOLUTIONINFO']._serialized_start=213
  _globals['_SOLUTIONINFO']._serialized_end=303
  _globals['_SUBMITREQUEST']._serialized_start=305
  _globals['_SUBMITREQUEST']._serialized_end=379
  _globals['_SUBMITRESPONSE']._serialized_start=381
  _globals['_SUBMITRESPONSE']._serialized_end=411
  _globals['_MINERADOR']._serialized_start=414
  _globals['_MINERADOR']._serialized_end=698
# @@protoc_insertion_point(module_scope)
