# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpcMiner_pb2 as grpcMiner__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpcMiner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MineradorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTransactionID = channel.unary_unary(
                '/Minerador/getTransactionID',
                request_serializer=grpcMiner__pb2.Empty.SerializeToString,
                response_deserializer=grpcMiner__pb2.TransactionID.FromString,
                _registered_method=True)
        self.getChallenge = channel.unary_unary(
                '/Minerador/getChallenge',
                request_serializer=grpcMiner__pb2.TransactionID.SerializeToString,
                response_deserializer=grpcMiner__pb2.Challenge.FromString,
                _registered_method=True)
        self.getTransactionStatus = channel.unary_unary(
                '/Minerador/getTransactionStatus',
                request_serializer=grpcMiner__pb2.TransactionID.SerializeToString,
                response_deserializer=grpcMiner__pb2.Status.FromString,
                _registered_method=True)
        self.getWinner = channel.unary_unary(
                '/Minerador/getWinner',
                request_serializer=grpcMiner__pb2.TransactionID.SerializeToString,
                response_deserializer=grpcMiner__pb2.Winner.FromString,
                _registered_method=True)
        self.getSolution = channel.unary_unary(
                '/Minerador/getSolution',
                request_serializer=grpcMiner__pb2.TransactionID.SerializeToString,
                response_deserializer=grpcMiner__pb2.SolutionInfo.FromString,
                _registered_method=True)
        self.submitChallenge = channel.unary_unary(
                '/Minerador/submitChallenge',
                request_serializer=grpcMiner__pb2.SubmitRequest.SerializeToString,
                response_deserializer=grpcMiner__pb2.SubmitResponse.FromString,
                _registered_method=True)


class MineradorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTransactionID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTransactionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWinner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSolution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MineradorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTransactionID': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactionID,
                    request_deserializer=grpcMiner__pb2.Empty.FromString,
                    response_serializer=grpcMiner__pb2.TransactionID.SerializeToString,
            ),
            'getChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.getChallenge,
                    request_deserializer=grpcMiner__pb2.TransactionID.FromString,
                    response_serializer=grpcMiner__pb2.Challenge.SerializeToString,
            ),
            'getTransactionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactionStatus,
                    request_deserializer=grpcMiner__pb2.TransactionID.FromString,
                    response_serializer=grpcMiner__pb2.Status.SerializeToString,
            ),
            'getWinner': grpc.unary_unary_rpc_method_handler(
                    servicer.getWinner,
                    request_deserializer=grpcMiner__pb2.TransactionID.FromString,
                    response_serializer=grpcMiner__pb2.Winner.SerializeToString,
            ),
            'getSolution': grpc.unary_unary_rpc_method_handler(
                    servicer.getSolution,
                    request_deserializer=grpcMiner__pb2.TransactionID.FromString,
                    response_serializer=grpcMiner__pb2.SolutionInfo.SerializeToString,
            ),
            'submitChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.submitChallenge,
                    request_deserializer=grpcMiner__pb2.SubmitRequest.FromString,
                    response_serializer=grpcMiner__pb2.SubmitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Minerador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Minerador', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Minerador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTransactionID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Minerador/getTransactionID',
            grpcMiner__pb2.Empty.SerializeToString,
            grpcMiner__pb2.TransactionID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Minerador/getChallenge',
            grpcMiner__pb2.TransactionID.SerializeToString,
            grpcMiner__pb2.Challenge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTransactionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Minerador/getTransactionStatus',
            grpcMiner__pb2.TransactionID.SerializeToString,
            grpcMiner__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getWinner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Minerador/getWinner',
            grpcMiner__pb2.TransactionID.SerializeToString,
            grpcMiner__pb2.Winner.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Minerador/getSolution',
            grpcMiner__pb2.TransactionID.SerializeToString,
            grpcMiner__pb2.SolutionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submitChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Minerador/submitChallenge',
            grpcMiner__pb2.SubmitRequest.SerializeToString,
            grpcMiner__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
